### ISSUE TITLE
11.1 포드의 자원 사용량 제한

### ISSUE THREAD

**Issue by qlqnf16** [sangw0804/study-docker#10]
# 11 애플리케이션 배포를 위한 고급 설정

## 11.1 포드의 자원 사용량 제한

서버의 자원을 효율적으로 사용하기 위해 각 컨테이너의 자원 사용량을 적절히 제한해야 한다. 다음과 같이 resources.limits 정의를 추가해 각 포드의 컨테이너가 가지는 자원의 양을 지정할 수 있다.

```yaml
spec:
    #...
     resources:
        limits:
        memory: "256Mi"
        cpu: "1000m"
```

포드를 생성 후, 포드가 생성된 노드를 describe 명령어로 확인하면 자원 할당량이 제한된 것을 확인할 수 있다.

resource-limit-pod 에는 limit 스펙을 정의하고, resource-limit-pod2 에는 원래 만들던 것처럼 limit을 정의하지 않았다. 정의하지 않을 경우 CPU Limits, Memory Limits 등이 `0` 으로 설정된다.

![Screen Shot 2021-05-14 at 3 08 09 PM](https://user-images.githubusercontent.com/37537216/118369811-d624c300-b5df-11eb-9f16-d69444132f61.png)

### Request

Limit이 컨테이너가 최대한으로 할당받을 수 있는 자원의 양을 의미한다면, Request는 최소한으로 가져야 하는 양을 의미한다. **최소한으로 가져야 하는 양**은 왜 정의해 줘야 하는걸까? 쿠버네티스의 오버커밋 때문이다.

오버커밋이란 <u>실제 물리적 자원이 가지는 양보다 더 많은 양의 자원을 할당</u>할 수 있게 해주는 것이다. 1000m 만큼의 CPU 자원이 있는 서버에 limit이 750mi 인 컨테이너 두 개를 배치시킬 수 있다는 뜻이다. 그래서 두 컨테이너의 사용량의 합이 1000m 를 넘지 않고, 각각 750mi를 넘지 않는 선에서 자원을 할당해 효율적으로 자원을 사용할 수 있다.

Request는 만약 두 컨테이너가 활용하려는 자원의 양의 합이 실제 물리적 자원의 양을 초과할 때 필요한 개념이다. 각각의 컨테이너가 Request를 500m 로 걸어놓는다면, 최소한 500m는 안전하게 사용가능하도록 보장받을 수 있다. 따라서 Limit은 물리적 자원을 초과해서 설정될 수 있지만, Request는 물리적 자원이 제공가능한 양을 초과할 수 없다.

```yaml
spec:
  containers:
    #...
    resources:
      limits:
        memory: "256Mi"
        cpu: "1000m"
      requests:
        memory: "128Mi"
        cpu: "500m"
```

### QoS (Quality of Service)

A컨테이너가 자신의 Request를 100% 사용하는 중에 B컨테이너의 사용량이 Request를 넘어 이 컨테이너를 침범하려 해서 자원 사용이 충돌하는 상황을 경합이 발생한다고 한다.

CPU에서 경합이 발생한 경우, 자원 사용에 실패한 컨테이너는 스로틀이 걸릴 뿐 사용에 큰 문제는 발생하지 않는다. 하지만 메모리에서 경합이 발생한 경우, 자원 사용에 실패한 프로세스는 **강제로 종료**된다. 포드가 종료되면 다른 노드로 옮겨지는 '퇴거'가 수행된다. 이 때 어느 포드부터 종료시킬 지 우선순위를 지정하는 클래스가 QoS다.

#### QoS의 종류

- Guaranteed: Limit과 Request가 완전히 동일할 때. (Spec에서 Limit만 정의하면 Request도 같은 값으로 설정된다.) 가장 높은 우선순위를 가진다.
- BestEffort: Limit/Request를 지정하지 않을 때. 우선순위가 가장 낮다.
- Burstable: Limit이 Request보다 클 때.

우선순위는 일반적으로 BestEffort, Burstable 순이지만 자원 사용량이 더 많을 수록 우선순위가 낮아지기 때문에 역전이 가능하다.

### ResourceQuota

포드와 마찬가지로 네임스페이스에 대해서도 자원 사용량을 제한할 수 있다. 이를 지정해주는 오브젝트가 ResourceQuota로, 네임스페이스가 총 할당받을 수 있는 자원의 limit과 request, 최대 생성 가능한 Pod, Service의 갯수를 정의해 줄 수 있다. quota를 지정한 후에 제한을 넘는 포드 생성 요청이 들어오면 에러가 발생한다.

`주의1` Deployment를 이용해 포드를 생성하려고 하면 에러는 발생하지 않지만 포드가 생성되지도 않는다. 포드 생성의 주체는 디플로이먼트가 아니라 레플리카셋이기 때문에, 에러로그는 레플리카셋에 남는다. 포드를 생성하기 위한 자원이 생긴다면 레플리카셋이 자동으로 다시 포드 생성을 시도할 수 있다.

`주의2` ResourceQuota를 생성할 때 아래와 같이 명시적으로 BestEffort의 포드 개수를 지정해줘야 한다. 그렇지 않으면 BestEffort 포드 생성시 에러가 난다.

```yaml
spec:
	hard:
		count/pods: 1
	scopes:
		- BestEffort
```

### LimitRange

LimitRange는 특정 네임스페이스에서 생성되는 포드나 컨테이너에 **할당되는 자원의 기본값**을 정해주는 오브젝트다. LimitRange 오브젝트를 생성해놓으면, 이후 그 네임스페이스 안에서 생성되는 포드는 자동으로 LimitRange에 설정된 limit, request 값을 가진다.
