### ISSUE TITLE
11.2 쿠버네티스 스케줄링

### ISSUE THREAD

**Issue by qlqnf16** [sangw0804/study-docker#11]
# 11.2 쿠버네티스 스케줄링

kubectl 로 포드를 생성할 때 쿠버네티스는 여러 노드 중 적절한 곳에 포드를 생성한다. 이를 관장하는 게 쿠버네티스 스케줄러인데, 노드 필터링과 노드 스코어링 단계를 거쳐 노드를 선택한다.

- 노드 필터링: 포드를 할당할 수 있는 노드를 거르는 단계
- 노드 스코어링: 노드의 점수를 계산하는 단계. 새로 생성되는 포드가 사용하려는 이미지가 이미 존재하는 노드이거나, 가용자원이 많은 노드가 높은 점수를 받는다

#### nodeName

말 그대로 포드가 생성될 노드를 이름으로 직접 지정하는 방법.

#### nodeSelector

label을 이용해 선택하는 방법. `mylabel/disk=ssd` 등 label을 가진 노드에 생성한다.

#### Node Affinity

nodeSelector에서 좀 더 확장된 기능. `operator` 를 이용해 In, NotIn, Exist 등으로 더 디테일한 조건 설정이 가능하다. 그리고 hard / soft 조건을 설정할 수 있는데, `hard` 는 조건을 만족하는 노드여야만 생성이 가능하고, `soft`는 조건을 만족하는 노드가 있다면 그곳에 생성하겠다는 의미다.

- `hard`: requiredDuringSchedulingIgnoredDuringExecution
- `soft`: prefferedDuringSchedulingIgnoredDuringExecution

#### Pod Affinity

nodeName, nodeSelector, Node Affinity는 노드의 조건을 지정하는 방식이다. Pod Affinity는 pod의 특성을 기준으로, 조건을 만족하는 포드와 같은 노드에 포드를 생성한다.

`podAntiAffinity` 를 사용하면 특정 조건을 가지는 포드가 **없는** 노드에 포드를 생성할 수 있다.

###

### Taints 와 Tolerations

Label 외에도 노드에 Taint를 설정해 스케줄링을 할 수 있다. Taint는 얼룩이라는 뜻으로, Taint가 설정된 노드엔 포드가 할당될 수 없다. 단 포드에 적절한 Toleration을 설정하면 Taint가 설정된 노드에도 할당할 수 있다.

```bash
kubectl taint node [nodename] [key]=[value]:[effect]
```

Label과 비슷하게 key-value 쌍으로 설정하며, taint가 노드에서 어떤 효과를 낼 지를 의미하는 effect를 명시한다.

#### effect의 종류

- NoSchedule: 포드를 스케줄링하지 않음
- NoExecute: 포드를 스케줄링하지 않음. 실행중인 포드가 있다면 중단시킴.
- PreferNoSchedule

#### Tolerations

Toleration는 포드에 설정한다. 아래처럼 설정하면 `alicek106/mytaint=dirty` 의 키-값 쌍을 가지면서 NoSchedule의 효과를 가진 노드에는 할당이 가능하다는 뜻.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration-test
spec:
  tolerations:
    - key: alicek106/my-taint
      value: dirty
      operator: Equal # alicek106/my-taint 키의 값이 dirty이며 (Equal)
      effect: NoSchedule # Taint 효과가 NoSchedule인 경우 해당 Taint를 용인
  containers:
    - name: nginx
      image: nginx:latest
```

operator를 `Eqaul`이 아니라 `Exists`로 설정할 수 있다. 이 경우는 와일드카드로 작동해 명시되지 않은 값은 모든 종류를 용인한다는 뜻이다.

```yaml
# 모든 종류의 Taint 용인
tolerations:
- operator: Exists

# my-key를 키로 가지는 Taint 용인
tolerations:
- key: my-key
	operator: Exists

# 키가 my-key고 NoExecute 효과인 Taint 용인
tolerations:
- key: my-key
	effect: NoExecute
	operator: Exists
```

#### tolerationSeconds

기본적으로 포드를 생성하면 아래와 같은 Toleration을 가진다. `not-ready`, `unreachable` 이라는 Taint에 대해 300초 동안 Toleration을 적용한다는 뜻이다. NoExecute의 경우 해당 노드에서 실행중인 포드도 종료하는데, tolearationSeconds에 설정된 시간동안 종료되지 않고 대기하다가 그 이후에 종료, 다른 노드로 옮겨간다.

![Screen Shot 2021-05-16 at 12 25 35 AM](https://user-images.githubusercontent.com/37537216/118369763-9d84e980-b5df-11eb-9552-962d32ecd59a.png)

### Cordon, Drain

Taint를 이용하지 않고 노드에 스케줄링을 막는 방법. Cordon은 `NoSchedule` 과, Drain은 `NoExecute` 와 같이 동작한다.

Drain을 사용할 경우, 노드에서 실행중이던 포드가 다른 노드로 생성돼야 하기 때문에 노드에 단일 포드가 있는 경우 drain 명령어가 실패한다. 또한 어플리케이션을 구동하기 위해 필요한 포드가 모두 drain 명령어에 의해 중지되는 것을 방지하기 위해 `PodDisruptionBudget` 오브젝트를 사용할 수 있다.
