### ISSUE TITLE
14. 쿠버네티스 모니터링

### ISSUE THREAD

**Issue by gyeol1212** [sangw0804/study-docker#15]
## WHY
- 장애 났을 때 확인해야 해서..
- 장애 날거 같을 때 확인해야 해서..
- 장애 안나게 하려고 현재 사용 패턴 분석해야 해서..

### 종류
- 쿠버네티스가 자체 제공하는 모니터링 X

#### 오픈소스
- 프로메테우스 : (가장 많이 사용) 성능, 사용성, 호환성 우수
- 그라파나 : 수집된 데이터 시각화
- AlertManager : 알람 보내기 등

#### 유료
- 데이터독
- 뉴렐릭
- CloudWatch

=> 적합한 걸 잘 찾아보자

## 구조
0. 엔드포인트 정보 지정
1. 프로메테우스와 같은 시스템이 `/metrics` 경로로 메트릭 요청
2. CAdvisor와 같은 모니터링 도구(exporter)가 시계열 메트릭 반환
3. 수집된 메트릭 저장

## 분류
- 인프라 수준의 메트릭: 호스트 레벨. 호스트에 마운트 된 디스크  사용량, 패킷 전송량 등등
- 컨테이너 수준의 메트릭: 컨테이너 레벨. 컨테이너별 CPU, 메모리 사용량, 프로세스 상태, 리소스 할당량 등등.. (CAdvisor)
- 애플리케이션 수준의 메트릭: 기타. 애플리케이션에 종속적인 ㄷ이터, 서버에서 제공하는 모니터링 데이터 등등..

## metrics-server
- 쿠버네티스가 제공하는 add-on
- 컨테이너와 인프라 레벨의 메트릭을 수집

#### 리소스 사용량 확인
```
$ kubectl top pods -n kube-system
$ kubectl top nodes
```

## kube-state-metrics
- 쿠버네티스 리소스의 상태에 관련된 메트릭을 제공하는 add-on
- 포드의 상태가 어떤지, 디플로이먼트 레플리카 개수가 몇 개인지
```
$ kubectl run --generator=run-pod/v1-i --tty --rm debug --image=alicek106/ubuntu:curl bash
# curl kube-state-metrics.kube-system.svc:8080/metrics
```

## node-exporter
- 인프라 수준의 메트릭을 제공하는 exporter (CAdvisor는 컨테이너 수준)
```
$ kubectl get po -o wide -n monitoring
```

## 프로메테우스
```
$ kubectl get svc
$ kubectl port-forward svc/prometheus-operated 19090:9090
```
`http://0.0.0.0:19090`

#### 수집할 메트릭 연결
```YAML
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor // 어떠한 서비스에 연결된 포드로부터 메트릭을 가져올지
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: v0.18.1
  name: node-exporter
  namespace: monitoring
spec:
   ...
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter

```

## Grapana
- 시각화 도구
```
$ kubectl apply -f grafana.yaml
$ kubectl port-forward svc/grafana 3000:3000
```
