### ISSUE TITLE
7. 쿠버네티스 리소스의 관리와 설정 

### ISSUE THREAD

**Issue by qlqnf16** [sangw0804/study-docker#6]
# 쿠버네티스 리소스의 관리와 설정

## 네임스페이스 (Namespace)

리소스를 **논리적으로** 구분하기 위해 제공하는 오브젝트. 포드, 레플리카셋 같은 쿠버네티스 리소스들이 묶여있는 그룹. 네임스페이스 별로 사용자 권한 등을 다르게 관리할 수 있다. 모니터링, 로드밸런싱 인그레스 등을 위해 사용한다.

하나의 클러스터를 개발/운영/테스트 3개의 네임스페이스로 나눠서 운영할 수 있다. 네임스페이스로 할 수 있는 것은

- 사용자별로 네임스페이스별 접근 권한을 다르게 운영할 수 있다.
- 네임스페이스별로 [리소스의 쿼타](https://kubernetes.io/docs/concepts/policy/resource-quotas/) (할당량)을 지정할 수 있다. 개발계에는 CPU 100, 운영계에는 CPU 400과 GPU 100개 식으로, 사용 가능한 리소스의 수를 지정할 수 있다. 
- 네임 스페이스별로 리소스를 나눠서 관리할 수 있다. (Pod, Service 등)

### 기본 네임스페이스의 종류

* default: 쿠버네티스를 설치하면 자동으로 사용하도록 설정되는 네임스페이스. --namespace 옵션을 명시하지 않고 kubernetes 명령을 실행할 때 기본적으로 사용됨.
* kube-system: 쿠버네티스 클러스터 구성에 필수적인 컴포넌트와 설정값 등이 존재. 잘 모르면 건드리지 말 것

### 네임스페이스에 속하거나, 속하지 않는 오브젝트

```bash
kubectl api-resources --namespaced=[true/false]
```

* namespaced: 포드, 서비스, 레플리카셋, 디플로이먼트 등

* 속하지 않은 오브젝트: 노드 등 클러스터 전반에 걸쳐 사용되는 오브젝트들

### 네임스페이스 간, 네임스페이스 내부의 통신

같은 네임스페이스에 존재하는 서비스는 **서비스명만으로 접근**할 수 있다. 예를 들어 앞 챕터에서 생성한 오브젝트는 모두 default  네임스페이스에서 생성됐기 때문에 `[서비스명]:[포트]` 형태로 접근이 가능했다. 하지만 만약 default 네임스페이스 안에 있는 오브젝트가 production 네임스페이스 내부의 서비스에 접근하려면 `[서비스명].[네임스페이스명].svc:[포트]` 처럼, **네임스페이스명을 명시**해줘야 한다.

## 컨피그맵 (Config Map), 시크릿 (Secret)

설정값을 포드에 전달하는 오브젝트. **YAML 파일과 설정값을 분리**할 수 있는 오브젝트로, 컨피그맵에는 설정값을, 시크릿에는 노출되면 안 되는 비밀값을 저장할 수 있다. 

![ConfigMap and Secret as Kubernetes Volumes?! 🤔 - DEV Community](https://res.cloudinary.com/practicaldev/image/fetch/s--j8CCiad9--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://static.wixstatic.com/media/e7182f_e8024feaeca04ea590c526305b51b47b%257Emv2.png)

### 컨피그맵

컨피그맵은 YAML 파일을 작성해 생성하거나, 쿠버네티스 명령으로 바로 생성할 수 있다.

```bash
kubectl create [configMap 이름] --from-literal [KEY]:[VALUE]
kubectl create [configMap 이름] --from-file [file 이름]
```

어플리케이션의 구조에 따라, 컨피그맵에 정의된 값을 **컨테이너의 환경변수로 사용**하거나, **포드 내부 파일로 마운트**해서 사용할 수 있다. 

#### 컨테이너의 환경 변수로 가져오기

```yaml
# 모두 가져오기
apiVersion: v1
kind: Pod
metadata:
  name: container-env-example
spec:
  containers:
#...
      envFrom:
      - configMapRef:
          name: log-level-configmap
      - configMapRef:
          name: start-k8s          
---
# 선택적으로 가져오기
 			env:
      - name: ENV_KEYNAME_1     # (1.1) 컨테이너에 새롭게 등록될 환경 변수 이름
        valueFrom: 
          configMapKeyRef:
            name: log-level-configmap
            key: LOG_LEVEL
      - name: ENV_KEYNAME_2  
        valueFrom: 
          configMapKeyRef:
            name: start-k8s      
            key: k8s             
```

`envFrom` 은 하나의 configMap에 존재하는 모든 key-value 값을 가져와 환경변수로 설정한다. `env`에서 `valueFrom`과 `configMapKeyRef`를 사용하면 컨테이너에 등록될 환경변수의 이름을 지정하고, configMap 에서 특정 키 값을 연결해줄 수 있다.

#### 파일로 마운트해서 가져오기

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
    - #...
      volumeMounts:
      - name: configmap-volume          # volumes에서 정의한 컨피그맵 볼륨 이름 
        mountPath: /etc/config             # 컨피그맵의 데이터가 위치할 경로

  volumes:
    - name: configmap-volume            # 컨피그맵 볼륨 이름
      configMap:
        name: start-k8s
        # 아래 items: 항목을 작성하면 선택적으로 가져오고, 작성하지 않으면 모두 가져옴
        items:
        - key: k8s
          path: k8s_fullname						# 포드에 저장되는 최종 파일명
```

`volumeMounts` 라는 값으로 포드 내에서 컨피그 파일이 위치할 곳을 지정한다. 이 때 사용되는 `volumeMounts.name` 은 바로 아래 `volumes` 에서 연결해주기 위한 가상의 이름이다. 실제로 configmap-volume 이라는 이름의 volume 이 생성되는 것은 아니다.

환경변수와 마찬가지로, configMap 의 모든 key-value 값을 가져올 수도 있고 선택적으로 가져올 수도 있다. 

### 시크릿

시크릿의 전반적인 사용방법은 컨피그맵과 같다. 다른 점은 생성할 때 더 다양한 타입을 제공한다는 것이다.

* `Opaque`/generic: 기본적으로 설정되는 타입. 사용자 정의 데이터를 저장

* `kubernetes.io/dockerconfigjson`: 사설 레지스트리에서 이미지를 받아올 때 사용

* `tls`: TLS 연결에 사용되는 공개키, 비밀키 등을 저장. 생성시 인증서와 키를 직접 명시해야 한다.

  ```bash
  kubectl create secret tls [이름] --cert [crt 파일명] --key [key 파일명]
  ```

이렇게 생성한 시크릿을 YAML 파일로 만들기 위해서 **kustomize** 를 사용할 수 있다. kustomize는 데이터를 YAML 파일로 분리하는 역할을 한다. 아래와 같은 형태로 kustomize YAML 파일을 작성할 수 있고, 지시문을 `configmapGenerator`로 설정하면 configMap YAML 파일도 생성할 수 있다. 

```yaml
secretGenerator:                # 시크릿을 생성하기 위한 지시문
- name: kustomize-secret
  type: kubernetes.io/tls       # tls 타입의 시크릿을 생성 
  files:
  - tls.crt=cert.crt            # tls.crt 라는 키에 cert.crt 파일의 내용을 저장
  - tls.key=cert.key            # tls.key 라는 키에 cert.key 파일의 내용을 저장
```
